services:
    richardhj.klarna_checkout.controller.push:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\Controller\Push
        public: true
        tags: ['controller.service_arguments']

    richardhj.klarna_checkout.controller.callback.address_update:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\Controller\AddressUpdate
        public: true
        tags: ['controller.service_arguments']

    richardhj.klarna_checkout.controller.callback.country_change:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\Controller\CountryChange
        public: true
        tags: ['controller.service_arguments']

    richardhj.klarna_checkout.controller.callback.shipping_option_update:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\Controller\ShippingOptionUpdate
        public: true
        tags: ['controller.service_arguments']

    richardhj.klarna_checkout.controller.callback.order_validation:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\Controller\OrderValidation
        public: true
        tags: ['controller.service_arguments']

    richardhj.klarna_checkout.hook_listener.find_surcharges_for_collection:
        class: Richardhj\IsotopeKlarnaCheckoutBundle\HookListener\FindSurchargesForCollectionListener
        public: true
